authorName: default
experimentName: example_auto-gbdt
trialConcurrency: 1
maxExecDuration: 1000h
maxTrialNum: 100
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space_metis.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: MetisTuner
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: /home/XXX/anaconda3/bin/python3 main.py
  codeDir: .
  gpuNum: 0