authorName: default
experimentName: example_model_retrain
trialConcurrency: 4
maxExecDuration: 48h
maxTrialNum: 100
#choice: local, remote, pai
trainingServicePlatform: local
#searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, NetworkMorphism
  #SMAC (SMAC should be installed through nnictl) 
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python model_retrain.py
  codeDir: .
  gpuNum: 1
