authorName: default
experimentName: example_cifar10-network-morphism
trialConcurrency: 4
maxExecDuration: 48h
maxTrialNum: 200
#choice: local, remote, pai
trainingServicePlatform: local
#searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, NetworkMorphism
  #SMAC (SMAC should be installed through nnictl) 
  builtinTunerName: NetworkMorphism
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
    #for now, we only support cv domain
    task: cv
    #input image width
    input_width: 32
    #input image channel
    input_channel: 3
    #output nums
    n_output_node: 10
trial:
  command: python cifar10-pytorch.py
  codeDir: .
  gpuNum: 1
