authorName: default
experimentName: example_auto-gbdt-BOHB
trialConcurrency: 1
maxExecDuration: 100h
maxTrialNum: 1000
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
advisor:
  #choice: Hyperband, BOHB
  builtinAdvisorName: BOHB
  classArgs:
    max_budget: 27
    min_budget: 1
    eta: 3
    optimize_mode: minimize
trial:
  command: /home/xuehui/anaconda3/bin/python main_advisor.py
  codeDir: .
  gpuNum: 0